CREATE OR REPLACE TASK XXX.XXX.SNOWFLAKE_MONGO_CHECKS_TAXONOMIES_TASK
	WAREHOUSE=DQ_XS_WH
	schedule='USING CRON 0 9 * * * America/Montevideo'
	as CALL XXX.XXX.SNOWFLAKE_MONGO_CHECKS('XXX','XXX','XXX.XXX.XXX');

ALTER TASK XXX.XXX.SNOWFLAKE_MONGO_CHECKS_TAXONOMIES_TASK RESUME;